/**
 * Built-in templates, ported from dataverse-gen's `_templates/*.ejs` to plain TypeScript functions.
 *
 * EJS compiles templates with `new Function`, which the iframe CSP of PPTB tools normally blocks, so the
 * templates are code instead. Whitespace (including a few odd indents and trailing tabs inherited from
 * the EJS originals) is reproduced on purpose so that files regenerated by `npx dataverse-gen` and by
 * this tool are identical and do not churn in source control.
 */
import type { ResolvedConfig } from './config';
import type { ComplexTypeModel, EntityModel, EnumModel, OperationModel, SchemaModel, TsType } from './types';

const HEADER = '/* eslint-disable*/\n';

function typeRef(type: TsType): string {
    return (type.importLocation ? `import("${type.importLocation}").` : '') + type.name;
}

function referenced(config: ResolvedConfig, key: string): { name: string; import: string } {
    const entry = config.referencedTypes[key];
    return { name: entry?.name ?? key, import: entry?.import ?? 'dataverse-ify' };
}

/** `entity.ejs` */
export function renderEntity(entity: EntityModel, config: ResolvedConfig): string {
    const lines: string[] = [HEADER.trimEnd()];
    const entityType = referenced(config, 'Entity');

    if (config.generateEntityTypes) {
        lines.push(`import { ${entityType.name} } from "${entityType.import}";`);
    }
    if (config.generateFormContext) {
        lines.push('');
        lines.push(`// Entity ${entity.SchemaName} FormContext`);
        lines.push(`export interface ${entity.SchemaName}FormContext extends Xrm.FormContext {`);
        lines.push('    getAttribute(): Xrm.Attributes.Attribute[];');
        lines.push('    getAttribute<T extends Xrm.Attributes.Attribute>(attributeName: string): T;');
        lines.push('    getAttribute(attributeName: string): Xrm.Attributes.Attribute;');
        lines.push('    getAttribute(index: number): Xrm.Attributes.Attribute;');
        lines.push('');
        lines.push('    getControl(): Xrm.Controls.Control[];');
        lines.push('    getControl<T extends Xrm.Controls.Control>(controlName: string): T;');
        lines.push('    getControl(controlName: string): Xrm.Controls.Control;');
        lines.push('    getControl(index: number): Xrm.Controls.Control;');
        lines.push('');
        for (const property of entity.Properties) {
            const type = property.TypescriptType;
            if (property.AttributeOf || property.SourceType !== 0 || type.name === 'Guid' || !type.definitelyTypedAttributeType) continue;
            lines.push('    /*');
            lines.push(`    ${property.Description}`);
            lines.push('    */');
            lines.push(`    getAttribute(name: '${property.Name}'): ${type.definitelyTypedAttributeType};`);
            lines.push('    /*');
            lines.push(`    ${property.Description}`);
            lines.push('    */');
            lines.push(`    getControl(name: '${property.Name}'): ${type.definitelyTypedControlType};`);
        }
        lines.push('}');
    }

    lines.push(`// Entity ${entity.SchemaName}`);
    lines.push(`export const ${entity.Name}Metadata = {`);
    lines.push(`  typeName: "mscrm.${entity.Name}",`);
    lines.push(`  logicalName: "${entity.Name}",`);
    lines.push(`  collectionName: "${entity.EntitySetName}",`);
    lines.push(`  primaryIdAttribute: "${entity.KeyName}",`);
    lines.push('  attributeTypes: {');
    lines.push('    // Numeric Types');
    for (const attribute of entity.Properties.filter((p) => p.TypescriptType.name === 'number')) {
        lines.push(`    ${attribute.Name}: "${attribute.Type.replace('Type', '')}",`);
    }
    lines.push('    // Optionsets');
    for (const attribute of entity.Properties.filter((p) => p.IsEnum)) {
        lines.push(`    ${attribute.Name}: "${attribute.IsMultiSelect ? 'MultiSelect' : 'Optionset'}",`);
    }
    lines.push('    // Date Formats');
    for (const attribute of entity.Properties.filter((p) => p.TypescriptType.name === 'Date')) {
        lines.push(`    ${attribute.Name}: "${attribute.Format}",`);
    }
    lines.push('  },');
    lines.push('  navigation: {');
    for (const nav of entity.NavigationProperties.filter((n) => !n.IsCollection)) {
        lines.push(`    ${nav.Name}: [${nav.Type.split(',').map((a) => `"${a}"`).join(',')}],`);
    }
    lines.push('  },');
    lines.push('};');
    lines.push('');
    lines.push('// Attribute constants');
    lines.push(`export const enum ${entity.SchemaName}Attributes {`);
    for (const property of entity.Properties) {
        lines.push(`  ${property.SchemaName} = "${property.Name}",`);
    }
    lines.push('}');

    if (config.generateEntityTypes) {
        lines.push('// Early Bound Interface');
        lines.push(`export interface ${entity.SchemaName || entity.Name} extends ${entityType.name} {`);
        for (const property of entity.Properties) {
            const comment =
                (property.DisplayName || '') +
                (property.IsRequired ? ' [Required]' : '') +
                (property.Type ? ' ' + property.Type : '') +
                (property.Description ? ' ' + property.Description : '') +
                (property.Format ? ' ' + property.Format : '');
            lines.push('  /*');
            lines.push(`  ${comment}`);
            lines.push('  */');
            lines.push(`  ${property.Name}?: ${typeRef(property.TypescriptType)}${property.IsRequired ? '' : ' | null'};`);
        }
        lines.push('}');
    }
    return lines.join('\n') + '\n';
}

/** `enum.ejs` */
export function renderEnum(enumModel: EnumModel): string {
    const lines: string[] = [HEADER.trimEnd()];
    lines.push(`// Enum ${enumModel.Name}`);
    lines.push(`export const enum ${enumModel.Name} {`);
    for (const member of enumModel.Members) {
        lines.push(enumModel.StringMembers ? `  ${member.Name} = "${member.Name}",` : `  ${member.Name} = ${member.Value},`);
    }
    lines.push('}');
    // The EJS template ends with "}\n  " (two trailing spaces after the final newline).
    return lines.join('\n') + '\n  ';
}

/** `action.ejs` / `function.ejs` */
export function renderOperation(operation: OperationModel, kind: 'action' | 'function', config: ResolvedConfig): string {
    const request = referenced(config, 'WebApiExecuteRequest');
    const structural = referenced(config, 'StructuralProperty');
    const operationType = referenced(config, 'OperationType');

    let out = HEADER;
    out += `import { ${request.name} } from "${request.import}";\n`;
    if (kind === 'action' || operation.Parameters.length > 0) {
        out += `import { ${structural.name} } from "${structural.import}";\n`;
    }
    out += `import { ${operationType.name} } from "${operationType.import}";\n`;
    out += '\n';
    out += `// Action ${operation.Name}\n`;
    out += `export const ${operation.Name}Metadata = {\n`;
    if (operation.IsBound) {
        out += `  boundParameter: "${operation.Parameters[0]?.Name ?? ''}",\n`;
    }
    out += '  parameterTypes: {\n';
    // Each loop iteration in the EJS source emits its body and then the two spaces that precede the
    // closing `<%});%>`, which is why every parameter after the first is indented by six spaces.
    for (const param of operation.Parameters) {
        out += `    "${param.Name}": {\n`;
        out += `      typeName: "${param.Type}",\n`;
        out += `      structuralProperty: ${structural.name}.${param.structuralTypeName}\n`;
        out += '      },\t\t\n';
        out += '  ';
    }
    out += '\n';
    out += '  },\n';
    out += `  operationType: ${operationType.name}.${kind === 'action' ? 'Action' : 'Function'},\n`;
    out += `  operationName: "${operation.Name}"\n`;
    out += '};\n';
    out += '\n';
    out += `export interface ${operation.Name}Request extends ${request.name} {\n`;
    for (const param of operation.Parameters) {
        out += `  ${param.Name}?: ${param.TypescriptTypes.map(typeRef).join(' | ')};\n`;
    }
    out += '}';
    return out;
}

/** `complextype.ejs` */
export function renderComplexType(complexType: ComplexTypeModel): string {
    let out = HEADER;
    out += `export interface ${complexType.Name} {\n`;
    for (const property of complexType.Properties) {
        out += `  ${property.Name}?: ${typeRef(property.TypescriptType)};\n`;
    }
    for (const property of complexType.NavigationProperties) {
        out += `  ${property.Name}?: ${typeRef(property.TypescriptType)};\n`;
    }
    out += '}';
    return out;
}

/** `metadata.ejs` */
export function renderMetadata(model: SchemaModel): string {
    let out = HEADER;
    for (const e of model.entities) out += `import { ${e.Name}Metadata } from "./entities/${e.SchemaName}";\n`;
    for (const a of model.actions) out += `import { ${a.Name}Metadata } from "./actions/${a.Name}";\n`;
    for (const f of model.functions) out += `import { ${f.Name}Metadata } from "./functions/${f.Name}";\n`;
    out += '\n';
    out += 'export const Entities = {\n';
    for (const e of model.entities) out += `  ${e.SchemaName}: "${e.Name}",\n`;
    out += '};\n';
    out += '\n';
    out += '// Setup Metadata\n';
    out += '// Usage: setMetadataCache(metadataCache);\n';
    out += 'export const metadataCache = {\n';
    out += '  entities: {\n';
    for (const e of model.entities) out += `    ${e.Name}: ${e.Name}Metadata,\n`;
    out += '  },\n';
    out += '  actions: {\n';
    for (const a of model.actions) out += `    ${a.Name}: ${a.Name}Metadata,\n`;
    for (const f of model.functions) out += `    ${f.Name}: ${f.Name}Metadata,\n`;
    out += '  }\n';
    out += '};';
    return out;
}

/** `index.ejs` — `fileNames` are output-root-relative paths of the files generated before it. */
export function renderIndex(fileNames: string[], fileSuffix: string): string {
    let out = HEADER;
    for (const file of fileNames) {
        const moduleName = file.replace(/\\/g, '/').replace(fileSuffix, '');
        out += `export * from "./${moduleName}";\n`;
    }
    return out;
}
