import { makeStyles, tokens } from "@fluentui/react-components";

export const useFieldPropertiesPanelStyles = makeStyles({
    root: {
        backgroundColor: tokens.colorNeutralBackground1,
        borderTopWidth: "1px",
        borderTopStyle: "solid",
        borderTopColor: tokens.colorNeutralStroke2,
        borderRightWidth: "1px",
        borderRightStyle: "solid",
        borderRightColor: tokens.colorNeutralStroke2,
        borderBottomWidth: "1px",
        borderBottomStyle: "solid",
        borderBottomColor: tokens.colorNeutralStroke2,
        borderLeftWidth: "1px",
        borderLeftStyle: "solid",
        borderLeftColor: tokens.colorNeutralStroke2,
        borderRadius: tokens.borderRadiusLarge,
        paddingTop: "18px",
        paddingBottom: "18px",
        paddingLeft: "18px",
        paddingRight: "18px",
        marginBottom: "12px",
    },
    eyebrow: {
        display: "block",
        fontFamily: "monospace",
        fontSize: "10.5px",
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        color: tokens.colorNeutralForeground3,
        marginBottom: "10px",
    },
    stageBadge: {
        display: "inline-block",
        fontSize: "11px",
        fontWeight: 600,
        color: "#ffffff",
        backgroundColor: "var(--stage-color)",
        paddingTop: "3px",
        paddingBottom: "3px",
        paddingLeft: "10px",
        paddingRight: "10px",
        borderRadius: "20px",
        marginBottom: "14px",
    },
    fieldName: {
        display: "block",
        fontSize: "18px",
        fontWeight: 700,
        marginBottom: "2px",
    },
    fieldLogical: {
        display: "block",
        fontFamily: "monospace",
        fontSize: "12px",
        color: tokens.colorNeutralForeground3,
        marginBottom: "14px",
        wordBreak: "break-all",
    },
    row: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: "12px",
        paddingTop: "10px",
        paddingBottom: "10px",
        borderTopWidth: "1px",
        borderTopStyle: "solid",
        borderTopColor: tokens.colorNeutralStroke2,
        fontSize: "13px",
    },
    firstRow: {
        borderTopWidth: 0,
        borderTopStyle: "none",
    },
    rowLabel: {
        color: tokens.colorNeutralForeground3,
        flexShrink: 0,
    },
    rowValue: {
        fontWeight: 500,
        textAlign: "right",
    },
});
