import { makeStyles, tokens } from "@fluentui/react-components";

export const useStagesFieldsStyles = makeStyles({
    flow: {
        position: "relative",
        display: "flex",
        flexDirection: "column",
        gap: "14px",
        "::before": {
            content: '""',
            position: "absolute",
            left: "19px",
            top: "22px",
            bottom: "22px",
            width: "2px",
            borderRadius: "2px",
            backgroundColor: tokens.colorNeutralStroke2,
        },
    },
    stage: {
        position: "relative",
        paddingLeft: "46px",
    },
    stageNode: {
        position: "absolute",
        left: "10px",
        top: "14px",
        width: "20px",
        height: "20px",
        borderRadius: "50%",
        backgroundColor: tokens.colorNeutralBackground1,
        borderTopWidth: "2px",
        borderTopStyle: "solid",
        borderTopColor: "var(--stage-color)",
        borderRightWidth: "2px",
        borderRightStyle: "solid",
        borderRightColor: "var(--stage-color)",
        borderBottomWidth: "2px",
        borderBottomStyle: "solid",
        borderBottomColor: "var(--stage-color)",
        borderLeftWidth: "2px",
        borderLeftStyle: "solid",
        borderLeftColor: "var(--stage-color)",
        zIndex: 2,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        "::after": {
            content: '""',
            width: "8px",
            height: "8px",
            borderRadius: "50%",
            backgroundColor: "var(--stage-color)",
        },
    },
    stageCard: {
        backgroundColor: tokens.colorNeutralBackground1,
        borderTopWidth: "1px",
        borderTopStyle: "solid",
        borderTopColor: tokens.colorNeutralStroke2,
        borderRightWidth: "1px",
        borderRightStyle: "solid",
        borderRightColor: tokens.colorNeutralStroke2,
        borderBottomWidth: "1px",
        borderBottomStyle: "solid",
        borderBottomColor: tokens.colorNeutralStroke2,
        borderLeftWidth: "1px",
        borderLeftStyle: "solid",
        borderLeftColor: tokens.colorNeutralStroke2,
        borderRadius: tokens.borderRadiusLarge,
        overflow: "hidden",
    },
    stageCardOpen: {
        borderTopColor: "var(--stage-color)",
        borderRightColor: "var(--stage-color)",
        borderBottomColor: "var(--stage-color)",
        borderLeftColor: "var(--stage-color)",
        boxShadow: tokens.shadow8,
    },
    stageHead: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
        width: "100%",
        paddingTop: "13px",
        paddingBottom: "13px",
        paddingLeft: "16px",
        paddingRight: "16px",
        border: "none",
        background: "none",
        cursor: "pointer",
        textAlign: "left",
        font: "inherit",
        color: tokens.colorNeutralForeground1,
    },
    stageHeadLeft: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
    },
    stageTitle: {
        fontWeight: 600,
        fontSize: "15px",
    },
    stageCount: {
        fontFamily: "monospace",
        fontSize: "11px",
        color: tokens.colorNeutralForeground3,
        backgroundColor: tokens.colorNeutralBackground3,
        borderTopWidth: "1px",
        borderTopStyle: "solid",
        borderTopColor: tokens.colorNeutralStroke2,
        borderRightWidth: "1px",
        borderRightStyle: "solid",
        borderRightColor: tokens.colorNeutralStroke2,
        borderBottomWidth: "1px",
        borderBottomStyle: "solid",
        borderBottomColor: tokens.colorNeutralStroke2,
        borderLeftWidth: "1px",
        borderLeftStyle: "solid",
        borderLeftColor: tokens.colorNeutralStroke2,
        paddingTop: "1px",
        paddingBottom: "1px",
        paddingLeft: "7px",
        paddingRight: "7px",
        borderRadius: "20px",
    },
    stageChevron: {
        flexShrink: 0,
        color: tokens.colorNeutralForeground3,
    },
    stageBody: {
        paddingTop: "4px",
        paddingBottom: "16px",
        paddingLeft: "16px",
        paddingRight: "16px",
        borderTopWidth: "1px",
        borderTopStyle: "solid",
        borderTopColor: tokens.colorNeutralStroke2,
    },
    stageEmpty: {
        display: "block",
        paddingTop: "16px",
        paddingBottom: "8px",
    },
    fieldList: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
        marginTop: "10px",
    },
    fieldChip: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        width: "100%",
        paddingTop: "9px",
        paddingBottom: "9px",
        paddingLeft: "10px",
        paddingRight: "10px",
        borderRadius: tokens.borderRadiusMedium,
        borderTopWidth: "1px",
        borderTopStyle: "solid",
        borderTopColor: "transparent",
        borderRightWidth: "1px",
        borderRightStyle: "solid",
        borderRightColor: "transparent",
        borderBottomWidth: "1px",
        borderBottomStyle: "solid",
        borderBottomColor: "transparent",
        borderLeftWidth: "1px",
        borderLeftStyle: "solid",
        borderLeftColor: "transparent",
        backgroundColor: tokens.colorNeutralBackground3,
        cursor: "pointer",
        textAlign: "left",
        font: "inherit",
        color: tokens.colorNeutralForeground1,
        ":hover": {
            borderTopColor: tokens.colorNeutralStroke1,
            borderRightColor: tokens.colorNeutralStroke1,
            borderBottomColor: tokens.colorNeutralStroke1,
            borderLeftColor: tokens.colorNeutralStroke1,
        },
    },
    fieldChipSelected: {
        backgroundColor: tokens.colorBrandBackground2,
        borderTopColor: tokens.colorBrandStroke1,
        borderRightColor: tokens.colorBrandStroke1,
        borderBottomColor: tokens.colorBrandStroke1,
        borderLeftColor: tokens.colorBrandStroke1,
    },
    fieldName: {
        fontSize: "13.5px",
        fontWeight: 500,
        flex: "1 1 auto",
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    fieldChevron: {
        flexShrink: 0,
        color: tokens.colorNeutralForeground3,
    },
});
